package com.dynalektric.model.repositories.project;

public class InputData {
    public double LINEVOLTSLV = 480;
    public String CONNECTIONTYPELV = "DELTA";
    public String CONNECTIONTYPEHV = "DELTA";
    public double LINEVOLTSHV = 32;
    public double KVA = 8;
    public String CONNECTION = "Dd0";
    public double FREQUENCY = 60.0;
    public double K = 97;
    public double WIREBARELV1 = 2.60;
    public double WIREBARELV2 = 2.60;
    public double WIREBAREHV1 = 10.0;
    public double WIREBAREHV2 = 3.5;
     public double NO_IN_PARALLEL_RA_LV1 = 1.0;
    public double NO_IN_PARALLEL_RA_LV2 = 1.0;
    public double NO_IN_PARALLEL_RA_HV1 = 1.0;
    public double NO_IN_PARALLEL_RA_HV2 = 2.0;
    public  String WINDINGTYPELV = "STRIP";
    public  String WINDINGTYPEHV = "STRIP";
    public String COOLING = "AN-Cl-F";
    public int LAYER_LV = 5;
    public int LAYER_HV = 3;
    public int OIL_DUCTS_AXIAL_LV = 0;
    public int TRANSPOSITION_LV = 0;
    public int TRANSPOSITION_HV = 0;
    public int COMP_GAP_LV = 0;
    public int COMP_GAP_HV = 0;
    public double INSULATION_LV = 0.10;
    public double INSULATION_HV = 0.10;
    public double END_CLEARANCES_LV = 40.0;
    public double END_CLEARANCES_HV = 43.0;
    public double INSULATION_BETWEEN_LAYERS_LV = 0.13;
    public double INSULATION_BETWEEN_LAYERS_HV = 0.13;
    public int OIL_DUCTS_RADIAL_LV1 = 1;
    public int OIL_DUCTS_RADIAL_LV2 = 8;
    public int OIL_DUCTS_RADIAL_HV1 = 1;
    public int OIL_DUCTS_RADIAL_HV2 = 8;

//    public Double CONDUCTIVITY_COPPER_90 = 44.7;
//    public Double CONDUCTIVITY_ALUMINIUM_90 = 28.0;
//    public Double CONDUCTIVITY_COPPER_115 = 42.76;
//    public Double CONDUCTIVITY_ALUMINIUM_115 = 26.73;

    public double FLUX_DENSITY = 1.4;
    public String STEEL_GRADE = "M4-27";
    public double STACKING_FACTOR = 0.95;
    public double CORE_BLDG_FACTOR = 2;
    public double CORE_W = 50.0;
    public int LIMB_PLATE_W = 0;
    public int LIMB_PLATE_D = 4;
    public int GAP_W = 16;
    public int GAP_D = 16;
    public int DELTA_W = 16;
    public int DELTA_D = 16;
    public int AM_W = 12;
    public int AM_D = 13;
    public String CONDUCTOR = "ALUMINIUM";
    public double WIND_TEMP = 90.0;
    public double CONDUCTIVITY = 28.0;
    public double BOM_CRCA_ENCL = 0.0;
}
